### ISSUE TITLE
Variable declaration errors

### ISSUE THREAD

**Issue by ashiklom** [tonygardella/BUGE512#4]
I'm getting $141 (Symbol declared but no values assigned -- usually means it hasn't been initialized) errors for the following lines:

```
 612           y_gross(t,c)=pro(t,c)*l(t,c)**(lshr) * k(t,c)**(1-lshr);
****                          $141
**** LINE      3 BATINCLUDE  /home/ashiklomanov/Documents/Unsynced/BUGE512/mosaic_economy_exe.gms
**** LINE    127 INPUT       /home/ashiklomanov/Documents/Unsynced/BUGE512/SLR.gms
 622           emiss_count(t,c)=(emiss_int(t,c) * y_net(t,c))/ mt2gt;
****                                     $141                      $140
```

**Comment by ashiklom** [comment]
Also the $140 error (Symbol undeclared) on mt2gt. What is that supposed to be?

**Comment by ashiklom** [comment]
I noticed you initialize `emiss_count("2010",c)` in your declarations, but then redefine it for the first time step in the execution (i.e. you have `emiss_count(t,c) = ...` with no `$(ord(t) > 1)`). Could this be part of the problem?

Also, is `emiss_int` the same as `aeei`? You never update `emiss_int(t,c)` in your code, but you do update `aeei(t,c)`, which you don't use anywhere else.

**Comment by parevalo** [comment]
emiss_int are different than aeei. I also use aeei in my code, it is actually a table imported in tony's code.

**Comment by ashiklom** [comment]
Fair enough. Here is a summary of the issues I found:
- Initial tech `a(t,c)` is only initialized in the first time step, i.e. it never changes as we move forward. If this is intentional, it shouldn't be declared as a matrix over time, just as a vector over country
- `emiss_count("2010", c)` is set prior to execution, and also in execution during the first time step.
- `prodgr` is declared, but never used. I'm assuming we need something like `pro(t,c) = thing * prodgr**(ord(t)-1)` in the economy declarations

**Comment by tonygardella** [comment]
sorry forgot to push

On Thu, Apr 16, 2015 at 12:58 PM, Paulo Arevalo notifications@github.com
wrote:

> emiss_int are different than aeei. I also use aeei in my code, it is
> actually a table imported in tony's code.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tonygardella/BUGE512/issues/4#issuecomment-93784848.

## 

Anthony Kenya Gardella
Work: +011(1) 619 669 8412
Undergraduate Student,
B.S. In Environmental Analysis & Policy,
Department of Earth & Environment, Boston University.

**Comment by ashiklom** [comment]
Cool, that fixed it!
