### ISSUE TITLE
Problem with emissions

### ISSUE THREAD

**Issue by parevalo** [tonygardella/BUGE512#7]
@tonygardella , could you check the emissions code? I checked the temperature changes and we are getting a 5 celsius degree increase over the course of the century, even with the original AEEI values. That's probably what's messing up with Alexey's and my code.

**Comment by tonygardella** [comment]
I'll check it out. What is a believable change in temperature over the next
century?

On Fri, May 1, 2015 at 12:23 PM, Paulo Arevalo notifications@github.com
wrote:

> @tonygardella https://github.com/tonygardella , could you check the
> emissions code? I checked the temperature changes and we are getting a 5
> celsius degree increase over the course of the century, even with the
> original AEEI values. That's probably what's messing up with Alexey's and
> my code.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tonygardella/BUGE512/issues/7.

## 

Anthony Kenya Gardella
Work: +011(1) 619 669 8412
Undergraduate Student,
B.S. In Environmental Analysis & Policy,
Department of Earth & Environment, Boston University
My Linkedin Account http://www.linkedin.com/in/anthonygardella

**Comment by ashiklom** [comment]
Here are the results (TATM -- temperature change from preindustrial) of running the DICE carbon model against fixed RCP8.5 emissions.

2010 0.800,    2015 0.875,    2020 0.939,    2025 0.994,    2030 1.044,    2035 1.090,    2040 1.134,    2045 1.176,    2050 1.219,    2055 1.263,    2060 1.309,    2065 1.357,    2070 1.408,    2075 1.463,    2080 1.520,    2085 1.580,    2090 1.642
2095 1.706,    2100 1.771

And here are the emissions themselves.

2010 9.167
2015 9.568
2020 9.969
2025 11.207
2030 12.444
2035 13.499
2040 14.554
2045 15.993
2050 17.432
2055 19.106
2060 20.781
2065 22.439
2070 24.097
2075 25.236
2080 26.374
2085 27.045
2090 27.715
2095 28.123
2100 28.531

Note that these emissions are in Gigatons of Carbon (NOT CO2). To get from CO2 to carbon, you multiply by 12/44, which is the ratio of their atomic weights.

**Comment by tonygardella** [comment]
See if my change makes a difference. I think I was using AEEI wrong in my
calculation. It should have a negative effect on emission growth,
countering the positive growth in the economy. I get a temperature change
of 2.659 now.

On Fri, May 1, 2015 at 1:21 PM, Alexey Shiklomanov <notifications@github.com

> wrote:
> 
> Here are the results (TATM -- temperature change from preindustrial) of
> running the DICE carbon model against fixed RCP8.5 emissions.
> 
> 2010 0.800, 2015 0.875, 2020 0.939, 2025 0.994, 2030 1.044, 2035 1.090,
> 2040 1.134, 2045 1.176, 2050 1.219, 2055 1.263, 2060 1.309, 2065 1.357,
> 2070 1.408, 2075 1.463, 2080 1.520, 2085 1.580, 2090 1.642
> 2095 1.706, 2100 1.771
> 
> And here are the emissions themselves.
> 
> 2010 9.167
> 2015 9.568
> 2020 9.969
> 2025 11.207
> 2030 12.444
> 2035 13.499
> 2040 14.554
> 2045 15.993
> 2050 17.432
> 2055 19.106
> 2060 20.781
> 2065 22.439
> 2070 24.097
> 2075 25.236
> 2080 26.374
> 2085 27.045
> 2090 27.715
> 2095 28.123
> 2100 28.531
> 
> Note that these emissions are in Gigatons of Carbon (NOT CO2). To get from
> CO2 to carbon, you multiply by 12/44, which is the ratio of their atomic
> weights.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tonygardella/BUGE512/issues/7#issuecomment-98181781.

## 

Anthony Kenya Gardella
Work: +011(1) 619 669 8412
Undergraduate Student,
B.S. In Environmental Analysis & Policy,
Department of Earth & Environment, Boston University
My Linkedin Account http://www.linkedin.com/in/anthonygardella

**Comment by ashiklom** [comment]
So it looks better, but our emissions are way too high.

Here is a plot of total global emissions (in GtC) from your code.
![world_emissions](https://cloud.githubusercontent.com/assets/5680221/7436855/8d60b14c-f01f-11e4-8a26-71ed2de3ece6.png)

And here is a plot of emissions by country.
![country_emissions](https://cloud.githubusercontent.com/assets/5680221/7436879/c49cdb9a-f01f-11e4-8e5c-ec782c1d9c54.png)

From the world emissions, you can clearly tell that the starting values are several times higher than the values from RCP 8.5. The latter starts at around 9, but our emissions starts at almost 30 GtC.

**Comment by ashiklom** [comment]
Scratch that, it actually looks correct now. I missed that we were dividing the world emissions by the 3.66 conversion from CO2 to C, so when you plot up those emissions, it's actually correct. We need to clarify the units in the emissions code.

**Comment by ashiklom** [comment]
Yeah, we just checked [Wikipedia](http://en.wikipedia.org/wiki/Representative_Concentration_Pathways) and our results for temperature line up pretty well with the RCP expectations. So the emissions and the resulting temperatures are correct!
